%============================================================================
% Function name.: bioprocessing_functions
% Date..........: April 6, 2020
% Author........: Eric F Schmiele
%                 (eric.robotic@gmail.com)
% Description...:
%                 shows the functions available at the
%                 "BIOPROCESSING_FUNCTIONS" folder:
%
%                   folder:
%                   add_emd
%                   add_fieldtrip
%                   choose_inputs
%                   correct_onset
%                   data2ft
%                   edfread
%                   eeg_corr
%                   eeg2tlck
%                   filter_no_dist
%                   find_on_and_offset
%                   find_thresh
%                   fourrier
%                   generate_emd_cost
%                   get_emd
%                   get_features
%                   get_index_from_peaks
%                   get_index_from_trigger
%                   getMAV
%                   getSSC
%                   getWL
%                   getZC
%                   limit_floor_and_ceiling
%                   organize_data_from_ewh
%                   percentage_confusion
%                   plotEEG
%                   power_freq_range
%                   read_EMG_data
%                   remove_eog_ica
%                   run_eeglab
%                   separate_trigger_channel
%                   source_calculation
%                   source_clear_show
%                   source_power
%                   source_psd
%                   source_rad
%                   source_threshold
%                   source_windowing
%                   source2eeg
%                   sources_corr
%                   sources_emd
%                   sources_in_time
%                   statistical_test
%                   svm_ensemble_crossval
%                   tlck_snr
%                   transform_position
%                   trialfun_using_trigger_signal
%============================================================================

function bioprocessing_functions()

%============================================================================
%% Display available function names
disp(['add_emd', 10,...
	'add_fieldtrip', 10,...
	'choose_inputs', 10,...
    'correct_onset', 10,...
	'data2ft', 10,...
	'edfread', 10,...
	'eeg_corr', 10,...
	'eeg2tlck', 10,...
	'filter_no_dist', 10,...
	'find_on_and_offset', 10,...
	'find_thresh', 10,...
	'fourrier', 10,...
	'generate_emd_cost', 10,...
	'get_emd', 10,...
	'get_features', 10,...
	'get_index_from_peaks', 10,...
	'get_index_from_trigger', 10,...
	'getMAV', 10,...
	'getSSC', 10,...
	'getWL', 10,...
	'getZC', 10,...
    'limit_floor_and_ceiling', 10,...
    'organize_data_from_ewh', 10,...
	'percentage_confusion', 10,...
	'plotEEG', 10,...
	'power_freq_range', 10,...
	'read_EMG_data', 10,...
	'remove_eog_ica', 10,...
	'run_eeglab', 10,...
	'separate_trigger_channel', 10,...
	'source_calculation', 10,...
	'source_clear_show', 10,...
	'source_power', 10,...
	'source_psd', 10,...
	'source_rad', 10,...
	'source_threshold', 10,...
	'source_windowing', 10,...
	'source2eeg', 10,...
	'sources_corr', 10,...
	'sources_emd', 10,...
	'sources_in_time', 10,...
	'statistical_test', 10,...
	'svm_ensemble_crossval', 10,...
	'tlck_snr', 10,...
	'transform_position', 10,...
	'trialfun_using_trigger_signal']);
%============================================================================

end
